import { useEffect } from 'react'
import {
  useAlerts
} from 'hooks'
import Head from 'next/head'
import Image from 'next/image'
import {
  makeStyles,
  Button,
  Container,
  Typography
} from '@material-ui/core'
import {KeyboardArrowRight} from '@material-ui/icons'
export default function Home() {

  const classes = useStyles()

  const {
    showAlertSuccess
  } = useAlerts()

  const handleClick = () => {
    showAlertSuccess("Welcome to the starter app!")
  }

  return (
    <div className={classes.root}>
      <Head>
        <title>Next.JS Starter App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="md" className={ classes.container }>
        <Typography variant='h1'>
          Next.JS + Material UI + GraphQL
        </Typography>
        <Typography variant='h5'>
          React starter application using Next.JS, GraphQL
        </Typography>
        <Button
          className={ classes.button }
          size='large'
          variant='contained'
          color='primary'
          onClick={ handleClick }
          endIcon={
            <KeyboardArrowRight />
          }
        >
          Let's Get Started
        </Button>
      </Container>
    </div>
  )
}


const useStyles = makeStyles(theme => ({
  root: {},
  button: {
    margin: theme.spacing(2,0),
    fontSize: 17,
    padding: theme.spacing(1.5,3)
  },
  container: {
    paddingTop: 200
  }
}))
