import { useAlerts } from 'hooks'
import Head from 'next/head'
import { 
  Box, 
  Button, 
  Container, 
  Typography 
} from '@mui/material';
import {KeyboardArrowRight} from '@mui/icons-material'

export default function Home() {

  const {
    showAlertSuccess
  } = useAlerts()

  const handleClick = () => {
    showAlertSuccess("Welcome to the starter app!")
  }

  return (
    <div style={ styles.root }>
      <Head>
        <title>Next.JS Starter App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="md" sx={ sx.container  }>
        <Typography variant='h1'>
          Next.JS + Material UI + GraphQL
        </Typography>
        <Typography variant='h5'>
          React starter application using Next.JS, GraphQL
        </Typography>
        <Button
          sx={ sx.button  }
          size='large'
          variant='contained'
          color='primary'
          onClick={ handleClick }
          endIcon={
            <KeyboardArrowRight />
          }
        >
          Let's Get Started
        </Button>
      </Container>
    </div>
  )
}

const styles = {
  root: {},
}

const sx = {
  button: {
    my: 2,
    mx: 0,    
    py: 1.5,
    px: 3,
    fontSize: 17,
  },
  container: {
    pt: 20
  }
}
